require:
  - rubocop-factory_bot
  - rubocop-rails

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/ClassAndModuleChildren:
  Enabled: false
